#!/bin/bash -eux

usage() {
  echo "Usage: $0" 1>&2
  exit 1
}

DIR="$( cd "$(dirname "$0")" ; pwd -P )"
export CUSTOM_COMPILE_COMMAND="$(basename "$0")"
export PYTHONPATH="${DIR}/third_party/py"

pushd "${DIR}"
if [ "$#" -eq 0 ] ; then
    bazelisk run //src:compile -- \
          --allow-unsafe \
          --generate-hashes \
          --no-emit-trusted-host \
          --no-annotate \
          --no-emit-find-links \
          --no-header \
          --no-index \
          --output-file="${DIR}/src/requirements.txt" \
          "${DIR}/src/requirements.in"

    # to update third_party/py run
    mv third_party/py/BUILD tmp_BUILD
    rm -rf third_party/py
    mkdir third_party/py
    mv tmp_BUILD third_party/py/BUILD
    bsci-python -m pip install -t third_party/py -r "${DIR}/src/requirements.txt" --no-deps

    bazelisk run //src:compile -- \
          --allow-unsafe \
          --no-emit-trusted-host \
          --no-annotate \
          --no-emit-find-links \
          --no-header \
          --no-index \
          --output-file="${DIR}/examples/tests/requirements.txt" \
          "${DIR}/examples/tests/requirements.in"

    # bazelisk test //... --test_output=errors

    # pushd examples
    # bazelisk test //... --test_output=errors
else
  usage
fi
